### ISSUE TITLE
Does not work across all LATS environments

### ISSUE THREAD

**Issue by esteinborn** [patik/lats-helper#7]
My new agency uses their own LATS, and thus use their own custom URL. 

AFAIK all LATS use some part of `lats.cma` in teh URL (EX: `https://oaglats.cma.com`)

Can you wildcard _lats.cma_ for applicable URLs for this extension?

**Comment by patik** [comment]
Unfortunately [Google doesn't allow wildcards like that](https://developer.chrome.com/extensions/match_patterns). Specifically, referring to your idea of `*lats.cma*`, they say "If '*' is in the host, it must be the first character" so that won't work.

I've updated an existing pattern to `*.cma.com`. This is a bit overkill since there are other services on that domain besides LATS, but the script should quickly detect this and exit. The only alternative would be to manually add every domain as it's brought to my attention.
